### ISSUE TITLE
Bug: We're sorry, but something went wrong while try add token for repo

### ISSUE THREAD

**Issue by fey** [kortirso/pullmetry#328]
I got an error when trying to add a token.
1. Open https://pullkeeper.dev/repositories/82563193-8aee-4858-9881-b30f87a3dfe7/access_tokens/new
2. Go to Fine-grained personal access tokens, create new token will `All repos, read only`
3. Add token created token `github_pat_xxxx`
4. got error on Save

Playload

```
authenticity_token: xxx
access_token[value]: github_pat_xxx
access_token[expired_at]: 
commit: Save access token
```

**Comment by fey** [comment]
Added Expiration time, `2025-01-01`. Saved correctly

**Comment by kortirso** [comment]
@fey thanks for issue, I have deployed last version where this bug is fixed already, token creation works, you can try again

**Comment by kortirso** [comment]
@fey and by security reasons selecting `All repos, read only` for access token is not a good choise, it's better to select only specific repositories for token with read only access to pull requests

**Comment by fey** [comment]
@kortirso But I created a token "for all repositories", :thinking: 500 error is that it won't let me create a token without Expiration time. I think there should be no such error if Expiration time is mandatory.

**Comment by kortirso** [comment]
there was bug while converting invalid value of expiration time (empty string in current case) - this is fixed
expiration time is optional here, it uses only for notifications

when you generate PAT token at Github - for security it's better to choose only specific repositories (but all repos can work too)

**Comment by kortirso** [comment]
in any case your token added to PullKeeper is valid, repository is synced and insights are generated
